### ISSUE TITLE
Need kruglendar on 2018 year

### ISSUE THREAD

**Issue by avdeev** [illus0r/kruglendar#1]

**Comment by illus0r** [comment]
@avdeev done :–)
https://github.com/illus0r/kruglendar/blob/gh-pages/dist/kruglendar-2018.pdf

**Comment by illus0r** [comment]
@avdeev could you show how do you use it? Pictures are most welcome!

**Comment by avdeev** [comment]
@illus0r Thank you!
No problem. As soon as I can.
